# Form implementation generated from reading ui file 'GUI01.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 372)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_title.setGeometry(QtCore.QRect(130, 10, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lb_title.setFont(font)
        self.lb_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_title.setObjectName("lb_title")
        self.gb_selectMode = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_selectMode.setGeometry(QtCore.QRect(100, 70, 271, 61))
        self.gb_selectMode.setObjectName("gb_selectMode")
        self.rb_TH2EN = QtWidgets.QRadioButton(parent=self.gb_selectMode)
        self.rb_TH2EN.setGeometry(QtCore.QRect(30, 30, 100, 20))
        self.rb_TH2EN.setObjectName("rb_TH2EN")
        self.rb_EN2TH = QtWidgets.QRadioButton(parent=self.gb_selectMode)
        self.rb_EN2TH.setGeometry(QtCore.QRect(160, 30, 100, 20))
        self.rb_EN2TH.setObjectName("rb_EN2TH")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 211, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pte_input = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.pte_input.setGeometry(QtCore.QRect(0, 20, 211, 121))
        self.pte_input.setObjectName("pte_input")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 130, 211, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tb_output = QtWidgets.QLabel(parent=self.groupBox_3)
        self.tb_output.setGeometry(QtCore.QRect(0, 20, 201, 121))
        self.tb_output.setText("")
        self.tb_output.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tb_output.setObjectName("tb_output")
        self.pb_process = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_process.setGeometry(QtCore.QRect(150, 280, 113, 32))
        self.pb_process.setObjectName("pb_process")
        self.pb_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_exit.setGeometry(QtCore.QRect(410, 280, 61, 32))
        self.pb_exit.setObjectName("pb_exit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 310, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_copy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_copy.setGeometry(QtCore.QRect(300, 280, 71, 32))
        self.pb_copy.setObjectName("pb_copy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TH-EN converter v1.0"))
        self.lb_title.setText(_translate("MainWindow", "TH-EN converter"))
        self.gb_selectMode.setTitle(_translate("MainWindow", "Select mode"))
        self.rb_TH2EN.setText(_translate("MainWindow", "TH --> EN"))
        self.rb_EN2TH.setText(_translate("MainWindow", "EN --> TH"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.pb_process.setText(_translate("MainWindow", "Process"))
        self.pb_exit.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "* Only Thai (Kedmanee) and US international keyboard layout"))
        self.pb_copy.setText(_translate("MainWindow", "Copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
